name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      GOPATH: ${{ github.workspace }}\go

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install RSRC
        shell: cmd
        run: |
          go install github.com/akavel/rsrc@latest
          echo "PATH=%PATH%;%GOPATH%\bin" >> "%GITHUB_ENV%"

      - name: Build executable
        shell: cmd
        run: build

      - name: Set version
        shell: cmd
        run: |
              set VERSION=${GITHUB_REF#refs/tags/}
              echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: EverCliping.exe
          generate_release_notes: false